build:
    environment:
        php:
            version: 7.1 # Common versions: 5.4, 5.5, 5.6, 7.0, 7.1, or hhvm
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
filter:
    excluded_paths:
        - 'bin/*'
        - 'public/vendor/*'
        - '*.min.js'
checks:
    php: true
    javascript: true
