build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          # https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer
          - php-scrutinizer-run
          # https://scrutinizer-ci.com/docs/tools/php/code-sniffer/
          - phpcs-run --standard=psr2 ./src

  # https://scrutinizer-ci.com/docs/build/languages#php
  environment:
    php:
      version: 7.4

# https://scrutinizer-ci.com/docs/reviews/excluding_files_from_analysis
filter:
  excluded_paths:
    - 'bin/*'
    - 'tests/*'
    - 'public/assets/*'
    - 'public/assets-admin/*'
    - 'public/vendor/*'
    - '*.min.js'

checks:
  php: true
  javascript: true

# https://scrutinizer-ci.com/docs/tools/external-code-coverage/
tools:
  external_code_coverage:
    timeout: 600
