language: php
os: linux
dist: bionic
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - docker

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

install:
  - rm composer.lock
  # https://stackoverflow.com/questions/51341463/unable-to-change-travis-ci-php-memory-limit/51381888#comment89735616_51381888
  - COMPOSER_MEMORY_LIMIT=-1 composer install
  - ./vendor/bin/simple-phpunit install

script:
  - ./bin/phpunit
  # this checks that the source code follows the Symfony Code Syntax rules
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
  # Ensures that arguments injected into services match type declarations
  - ./bin/console lint:container
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config --parse-tags
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates
  # this checks that the YAML translations contain no syntax errors
  - ./bin/console lint:yaml translations
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  # TRAVIS keeps failing "An error occurred: gnutls_handshake() failed: Handshake failed."
  - ./bin/console security:check
  # this checks that the composer.json and composer.lock files are valid
  #- composer validate --strict
  # this checks that Doctrine's mapping configurations are valid
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.4" ]]; then ./docker/build/travis.sh; fi
