version: "3.4"

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--password=password" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony

  php:
    build:
      context: .
      target: php
      cache_from:
        - ${PHP_IMAGE_CACHE:-d3strukt0r/openstore-api-php}
    image: ${PHP_IMAGE:-d3strukt0r/openstore-api-php}
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - .:/app:rw,cached
    environment:
      OAUTH_CLIENT_ID: local
      OAUTH_CLIENT_SECRET: 69c5cfaac2c52f6fa69532a2f3149642c925931b54404453f62d342b62556b8f
      APP_ENV: dev
      APP_SECRET: e1797e35ef3cbe7530cee429fcefa53d
      #TRUSTED_PROXIES=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      #TRUSTED_HOSTS='^(localhost|example\.com)$'
      MAILER_DSN: null://null
      DATABASE_URL: mysql://root:password@db:3306/symfony?serverVersion=5.7
      GOOGLE_RECAPTCHA_SITE_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      GOOGLE_RECAPTCHA_SECRET: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

  nginx:
    build:
      context: .
      target: nginx
      cache_from:
        - ${PHP_IMAGE_CACHE:-d3strukt0r/openstore-api-php}
        - ${NGINX_IMAGE_CACHE:-d3strukt0r/openstore-api-nginx}
    image: ${NGINX_IMAGE:-d3strukt0r/openstore-api-nginx}
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 80:80
      # - 443:443
    # environment:
    #   USE_HTTPS: "true"

networks:
  internal:
    external: false

volumes:
  database:
