version: "3.4"

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - internal
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - internal
    ports:
      - 8001:80
    environment:
      UPLOAD_LIMIT: 100M

  php:
    build:
      context: .
      target: php
      args:
        ENV: "dev"
    depends_on:
      - db
    networks:
      - internal
    environment:
      UPLOAD_LIMIT: 100M

      OAUTH_CLIENT_ID: local
      OAUTH_CLIENT_SECRET: 69c5cfaac2c52f6fa69532a2f3149642c925931b54404453f62d342b62556b8f

      ###> symfony/framework-bundle ###
      APP_ENV: dev
      APP_SECRET: e1797e35ef3cbe7530cee429fcefa53d
      #TRUSTED_PROXIES=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      #TRUSTED_HOSTS='^(localhost|example\.com)$'
      ###< symfony/framework-bundle ###

      ###> symfony/mailer ###
      MAILER_DSN: null://null
      ###< symfony/mailer ###

      ###> doctrine/doctrine-bundle ###
      # Format described at https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
      # For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data.db"
      # For a PostgreSQL database, use: "postgresql://db_user:db_password@127.0.0.1:5432/db_name?serverVersion=11&charset=utf8"
      # IMPORTANT: You MUST configure your server version, either here or in config/packages/doctrine.yaml
      DATABASE_URL: mysql://root:password@db:3306/symfony?serverVersion=5.7
      ###< doctrine/doctrine-bundle ###

      ###> google/recaptcha ###
      # To use Google Recaptcha, you must register a site on Recaptcha's admin panel:
      # https://www.google.com/recaptcha/admin
      # https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do
      GOOGLE_RECAPTCHA_SITE_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      GOOGLE_RECAPTCHA_SECRET: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      ###< google/recaptcha ###

  web:
    build:
      context: .
      target: nginx
      args:
        DEV: "true"
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 8000:80
    environment:
      UPLOAD_LIMIT: 100M

networks:
  internal:
    external: false

volumes:
  database:
